const HomeProduct =
[
    {
        id: 1,
        Name: 'product1',
        price: '26',
        image: "image/product1.png",
        cat: 'shirt',
        disc: 'A confortable shirt',
        type: 'new',
    },
    {
        id: 2,
        Name: 'product2',
        price: '46',
        image: "image/product2.png",
        cat: 'flannel',
        disc: 'A confortable Flannel',
        type: 'new',
    },
    {
        id: 3,
        Name: 'product3',
        price: '56',
        image: "image/product3.png",
        cat: 'jacket',
        disc: 'A confortable Jacket',
        type: 'featured',
    },
    {
        id: 4,
        Name: 'product4',
        price: '76',
        image: "image/placeholder.webp",
        cat: 'jacket',
        disc: 'Insert Disc',
        type: 'featured',
    },
    {
        id: 5,
        Name: 'product5',
        price: '56',
        image: "image/placeholder.webp",
        cat: 'flannel',
        disc: 'Insert Disc',
        type: 'featured',
    },
    {
        id: 6,
        Name: 'product6',
        price: '56',
        image: "image/placeholder.webp",
        cat: 'flannel',
        disc: 'Insert Disc',
        type: 'featured',
    },
    {
        id: 7,
        Name: 'product7',
        price: '56',
        image: "image/placeholder.webp",
        cat: '',
        disc: 'Insert Disc',
        type: 'top',
    },
    {
        id: 8,
        Name: 'product8',
        price: '5655',
        image: "image/placeholder.webp",
        cat: '',
        disc: 'Insert Disc',
        type: 'top',
    }
]

export default HomeProduct